CREATE TABLE IF NOT EXISTS `#__contractor` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `owner` int(11) NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `type` char(1) COLLATE utf8_unicode_ci NOT NULL DEFAULT '1',
  `positionInCompany` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `companyName` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `websiteUrl` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `phone` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(266) COLLATE utf8_unicode_ci NOT NULL,
  `trade` varchar(127) COLLATE utf8_unicode_ci NOT NULL,
  `nip` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `regon` varchar(14) COLLATE utf8_unicode_ci DEFAULT NULL,
  `bankAccountNumber` varchar(34) COLLATE utf8_unicode_ci NOT NULL,
  `billAddressStreet` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `billAddressCity` varchar(127) COLLATE utf8_unicode_ci NOT NULL,
  `billAddressState` varchar(127) COLLATE utf8_unicode_ci NOT NULL,
  `billAddressPostalCode` varchar(16) COLLATE utf8_unicode_ci NOT NULL,
  `billAddressCountry` varchar(127) COLLATE utf8_unicode_ci NOT NULL,
  `shippAddressStreet` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `shippAddressCity` varchar(127) COLLATE utf8_unicode_ci NOT NULL,
  `shippAddressState` varchar(127) COLLATE utf8_unicode_ci NOT NULL,
  `shippAddressPostalCode` varchar(16) COLLATE utf8_unicode_ci NOT NULL,
  `shippAddressCountry` varchar(127) COLLATE utf8_unicode_ci NOT NULL,
  `description` text COLLATE utf8_unicode_ci NOT NULL,
  `created` int(11) NOT NULL,
  `modified` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `owner` (`owner`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;
